### ISSUE TITLE
smtp-internal

### ISSUE THREAD

**Issue by Gazza7205** [CAAPIM/portal-helm-charts#3]
Error on helm install caused by ==> /templates/_helpers.tpl

Certificates generated using _/scripts/create_self_signed_certs.sh_ 

References files/smtp-internal.pem (doesn't exist) ==> should be files/smtp-internal.p12

> {{- define "smtp-internal-pem" -}}
>     {{- $f:= (.Files.Get "files/smtp-internal.pem")  }}
>     {{- if empty $f }}
>         {{- fail "Please place the SMTP Postfix CA pem in the files directory" }}
>     {{- else }}
>         {{- print $f }}
>     {{- end }}
> {{- end -}}

**Comment by amoghsa** [comment]
We are working on this. We will update ticket once an update has been made.

**Comment by ken-chou** [comment]
Your solution described is incorrect because the .p12 is a pkcs12 packed version of the .crt and .key file. The smtp container takes a CA certificate, PEM-format SSL certificate and corresponding SSL key as three separate environment variables.
